# https://ansible.readthedocs.io/projects/builder/en/latest/definition/
version: 3
dependencies:
  ansible_core:
    package_pip: ansible-core==2.16.7
  ansible_runner:
    package_pip: ansible-runner==2.4.1
  python_interpreter:
    package_system: python3.12
    python_path: /usr/bin/python3.12
  system: dependencies/bindep.txt
  galaxy: dependencies/requirements.yml
  python: dependencies/requirements.txt
images:
  base_image:
    name: quay.io/centos/centos:stream9
additional_build_files:
  - src: files/ansible.cfg
    dest: configs
additional_build_steps:
  prepend_base:
    - RUN dnf install -y --allowerasing curl
